[package]
name = "fef"
authors = ["Jiří Cihelka"]
description = "Rust implementation of a parser of the FEF format"
repository = "https://github.com/jiricekcz/fef-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
